interface MccCategory {
  id: string;
  category: string;
}

const mccCategories: Array<MccCategory> = [
  { id: "742", category: "Health Services" },
  { id: "763", category: "Other" },
  { id: "780", category: "Other" },
  { id: "1520", category: "Other" },
  { id: "1711", category: "Other" },
  { id: "1731", category: "Other" },
  { id: "1740", category: "Other" },
  { id: "1750", category: "Other" },
  { id: "1761", category: "Other" },
  { id: "1771", category: "Other" },
  { id: "1799", category: "Other" },
  { id: "2741", category: "Other" },
  { id: "2791", category: "Other" },
  { id: "2842", category: "Other" },
  { id: "3000", category: "Airline" },
  { id: "3001", category: "Airline" },
  { id: "3002", category: "Airline" },
  { id: "3003", category: "Airline" },
  { id: "3004", category: "Airline" },
  { id: "3005", category: "Airline" },
  { id: "3006", category: "Airline" },
  { id: "3007", category: "Airline" },
  { id: "3008", category: "Airline" },
  { id: "3009", category: "Airline" },
  { id: "3010", category: "Airline" },
  { id: "3011", category: "Airline" },
  { id: "3012", category: "Airline" },
  { id: "3013", category: "Airline" },
  { id: "3014", category: "Airline" },
  { id: "3015", category: "Airline" },
  { id: "3016", category: "Airline" },
  { id: "3017", category: "Airline" },
  { id: "3018", category: "Airline" },
  { id: "3019", category: "Airline" },
  { id: "3020", category: "Airline" },
  { id: "3021", category: "Airline" },
  { id: "3022", category: "Airline" },
  { id: "3023", category: "Airline" },
  { id: "3024", category: "Airline" },
  { id: "3025", category: "Airline" },
  { id: "3026", category: "Airline" },
  { id: "3027", category: "Airline" },
  { id: "3028", category: "Airline" },
  { id: "3029", category: "Airline" },
  { id: "3030", category: "Airline" },
  { id: "3031", category: "Airline" },
  { id: "3032", category: "Airline" },
  { id: "3033", category: "Airline" },
  { id: "3034", category: "Airline" },
  { id: "3035", category: "Airline" },
  { id: "3036", category: "Airline" },
  { id: "3037", category: "Airline" },
  { id: "3038", category: "Airline" },
  { id: "3039", category: "Airline" },
  { id: "3040", category: "Airline" },
  { id: "3041", category: "Airline" },
  { id: "3042", category: "Airline" },
  { id: "3043", category: "Airline" },
  { id: "3044", category: "Airline" },
  { id: "3045", category: "Airline" },
  { id: "3046", category: "Airline" },
  { id: "3047", category: "Airline" },
  { id: "3048", category: "Airline" },
  { id: "3049", category: "Airline" },
  { id: "3050", category: "Airline" },
  { id: "3051", category: "Airline" },
  { id: "3052", category: "Airline" },
  { id: "3053", category: "Airline" },
  { id: "3054", category: "Airline" },
  { id: "3055", category: "Airline" },
  { id: "3056", category: "Airline" },
  { id: "3057", category: "Airline" },
  { id: "3058", category: "Airline" },
  { id: "3059", category: "Airline" },
  { id: "3060", category: "Airline" },
  { id: "3061", category: "Airline" },
  { id: "3062", category: "Airline" },
  { id: "3063", category: "Airline" },
  { id: "3064", category: "Airline" },
  { id: "3065", category: "Airline" },
  { id: "3066", category: "Airline" },
  { id: "3067", category: "Airline" },
  { id: "3068", category: "Airline" },
  { id: "3069", category: "Airline" },
  { id: "3070", category: "Airline" },
  { id: "3071", category: "Airline" },
  { id: "3072", category: "Airline" },
  { id: "3073", category: "Airline" },
  { id: "3074", category: "Airline" },
  { id: "3075", category: "Airline" },
  { id: "3076", category: "Airline" },
  { id: "3077", category: "Airline" },
  { id: "3078", category: "Airline" },
  { id: "3079", category: "Airline" },
  { id: "3080", category: "Airline" },
  { id: "3081", category: "Airline" },
  { id: "3082", category: "Airline" },
  { id: "3083", category: "Airline" },
  { id: "3084", category: "Airline" },
  { id: "3085", category: "Airline" },
  { id: "3086", category: "Airline" },
  { id: "3087", category: "Airline" },
  { id: "3088", category: "Airline" },
  { id: "3089", category: "Airline" },
  { id: "3090", category: "Airline" },
  { id: "3091", category: "Airline" },
  { id: "3092", category: "Airline" },
  { id: "3093", category: "Airline" },
  { id: "3094", category: "Airline" },
  { id: "3095", category: "Airline" },
  { id: "3096", category: "Airline" },
  { id: "3097", category: "Airline" },
  { id: "3098", category: "Airline" },
  { id: "3099", category: "Airline" },
  { id: "3100", category: "Airline" },
  { id: "3101", category: "Airline" },
  { id: "3102", category: "Airline" },
  { id: "3103", category: "Airline" },
  { id: "3104", category: "Airline" },
  { id: "3105", category: "Airline" },
  { id: "3106", category: "Airline" },
  { id: "3107", category: "Airline" },
  { id: "3108", category: "Airline" },
  { id: "3109", category: "Airline" },
  { id: "3110", category: "Airline" },
  { id: "3111", category: "Airline" },
  { id: "3112", category: "Airline" },
  { id: "3113", category: "Airline" },
  { id: "3114", category: "Airline" },
  { id: "3115", category: "Airline" },
  { id: "3116", category: "Airline" },
  { id: "3117", category: "Airline" },
  { id: "3118", category: "Airline" },
  { id: "3119", category: "Airline" },
  { id: "3120", category: "Airline" },
  { id: "3121", category: "Airline" },
  { id: "3122", category: "Airline" },
  { id: "3123", category: "Airline" },
  { id: "3124", category: "Airline" },
  { id: "3125", category: "Airline" },
  { id: "3126", category: "Airline" },
  { id: "3127", category: "Airline" },
  { id: "3128", category: "Airline" },
  { id: "3129", category: "Airline" },
  { id: "3130", category: "Airline" },
  { id: "3131", category: "Airline" },
  { id: "3132", category: "Airline" },
  { id: "3133", category: "Airline" },
  { id: "3134", category: "Airline" },
  { id: "3135", category: "Airline" },
  { id: "3136", category: "Airline" },
  { id: "3137", category: "Airline" },
  { id: "3138", category: "Airline" },
  { id: "3139", category: "Airline" },
  { id: "3140", category: "Airline" },
  { id: "3141", category: "Airline" },
  { id: "3142", category: "Airline" },
  { id: "3143", category: "Airline" },
  { id: "3144", category: "Airline" },
  { id: "3145", category: "Airline" },
  { id: "3146", category: "Airline" },
  { id: "3147", category: "Airline" },
  { id: "3148", category: "Airline" },
  { id: "3149", category: "Airline" },
  { id: "3150", category: "Airline" },
  { id: "3151", category: "Airline" },
  { id: "3152", category: "Airline" },
  { id: "3153", category: "Airline" },
  { id: "3154", category: "Airline" },
  { id: "3155", category: "Airline" },
  { id: "3156", category: "Airline" },
  { id: "3157", category: "Airline" },
  { id: "3158", category: "Airline" },
  { id: "3159", category: "Airline" },
  { id: "3160", category: "Airline" },
  { id: "3161", category: "Airline" },
  { id: "3162", category: "Airline" },
  { id: "3163", category: "Airline" },
  { id: "3164", category: "Airline" },
  { id: "3165", category: "Airline" },
  { id: "3166", category: "Airline" },
  { id: "3167", category: "Airline" },
  { id: "3168", category: "Airline" },
  { id: "3169", category: "Airline" },
  { id: "3170", category: "Airline" },
  { id: "3171", category: "Airline" },
  { id: "3172", category: "Airline" },
  { id: "3173", category: "Airline" },
  { id: "3174", category: "Airline" },
  { id: "3175", category: "Airline" },
  { id: "3176", category: "Airline" },
  { id: "3177", category: "Airline" },
  { id: "3178", category: "Airline" },
  { id: "3179", category: "Airline" },
  { id: "3180", category: "Airline" },
  { id: "3181", category: "Airline" },
  { id: "3182", category: "Airline" },
  { id: "3183", category: "Airline" },
  { id: "3184", category: "Airline" },
  { id: "3185", category: "Airline" },
  { id: "3186", category: "Airline" },
  { id: "3187", category: "Airline" },
  { id: "3188", category: "Airline" },
  { id: "3189", category: "Airline" },
  { id: "3190", category: "Airline" },
  { id: "3191", category: "Airline" },
  { id: "3192", category: "Airline" },
  { id: "3193", category: "Airline" },
  { id: "3194", category: "Airline" },
  { id: "3195", category: "Airline" },
  { id: "3196", category: "Airline" },
  { id: "3197", category: "Airline" },
  { id: "3198", category: "Airline" },
  { id: "3199", category: "Airline" },
  { id: "3200", category: "Airline" },
  { id: "3201", category: "Airline" },
  { id: "3202", category: "Airline" },
  { id: "3203", category: "Airline" },
  { id: "3204", category: "Airline" },
  { id: "3205", category: "Airline" },
  { id: "3206", category: "Airline" },
  { id: "3207", category: "Airline" },
  { id: "3208", category: "Airline" },
  { id: "3209", category: "Airline" },
  { id: "3210", category: "Airline" },
  { id: "3211", category: "Airline" },
  { id: "3212", category: "Airline" },
  { id: "3213", category: "Airline" },
  { id: "3214", category: "Airline" },
  { id: "3215", category: "Airline" },
  { id: "3216", category: "Airline" },
  { id: "3217", category: "Airline" },
  { id: "3218", category: "Airline" },
  { id: "3219", category: "Airline" },
  { id: "3220", category: "Airline" },
  { id: "3221", category: "Airline" },
  { id: "3222", category: "Airline" },
  { id: "3223", category: "Airline" },
  { id: "3224", category: "Airline" },
  { id: "3225", category: "Airline" },
  { id: "3226", category: "Airline" },
  { id: "3227", category: "Airline" },
  { id: "3228", category: "Airline" },
  { id: "3229", category: "Airline" },
  { id: "3230", category: "Airline" },
  { id: "3231", category: "Airline" },
  { id: "3232", category: "Airline" },
  { id: "3233", category: "Airline" },
  { id: "3234", category: "Airline" },
  { id: "3235", category: "Airline" },
  { id: "3236", category: "Airline" },
  { id: "3237", category: "Airline" },
  { id: "3238", category: "Airline" },
  { id: "3239", category: "Airline" },
  { id: "3240", category: "Airline" },
  { id: "3241", category: "Airline" },
  { id: "3242", category: "Airline" },
  { id: "3243", category: "Airline" },
  { id: "3244", category: "Airline" },
  { id: "3245", category: "Airline" },
  { id: "3246", category: "Airline" },
  { id: "3247", category: "Airline" },
  { id: "3248", category: "Airline" },
  { id: "3249", category: "Airline" },
  { id: "3250", category: "Airline" },
  { id: "3251", category: "Airline" },
  { id: "3252", category: "Airline" },
  { id: "3253", category: "Airline" },
  { id: "3254", category: "Airline" },
  { id: "3255", category: "Airline" },
  { id: "3256", category: "Airline" },
  { id: "3257", category: "Airline" },
  { id: "3258", category: "Airline" },
  { id: "3259", category: "Airline" },
  { id: "3260", category: "Airline" },
  { id: "3261", category: "Airline" },
  { id: "3262", category: "Airline" },
  { id: "3263", category: "Airline" },
  { id: "3264", category: "Airline" },
  { id: "3265", category: "Airline" },
  { id: "3266", category: "Airline" },
  { id: "3267", category: "Airline" },
  { id: "3268", category: "Airline" },
  { id: "3269", category: "Airline" },
  { id: "3270", category: "Airline" },
  { id: "3271", category: "Airline" },
  { id: "3272", category: "Airline" },
  { id: "3273", category: "Airline" },
  { id: "3274", category: "Airline" },
  { id: "3275", category: "Airline" },
  { id: "3276", category: "Airline" },
  { id: "3277", category: "Airline" },
  { id: "3278", category: "Airline" },
  { id: "3279", category: "Airline" },
  { id: "3280", category: "Airline" },
  { id: "3281", category: "Airline" },
  { id: "3282", category: "Airline" },
  { id: "3283", category: "Airline" },
  { id: "3284", category: "Airline" },
  { id: "3285", category: "Airline" },
  { id: "3286", category: "Airline" },
  { id: "3287", category: "Airline" },
  { id: "3288", category: "Airline" },
  { id: "3289", category: "Airline" },
  { id: "3290", category: "Airline" },
  { id: "3291", category: "Airline" },
  { id: "3292", category: "Airline" },
  { id: "3293", category: "Airline" },
  { id: "3294", category: "Airline" },
  { id: "3295", category: "Airline" },
  { id: "3296", category: "Airline" },
  { id: "3297", category: "Airline" },
  { id: "3298", category: "Airline" },
  { id: "3299", category: "Airline" },
  { id: "3351", category: "Car Rental" },
  { id: "3352", category: "Car Rental" },
  { id: "3353", category: "Car Rental" },
  { id: "3354", category: "Car Rental" },
  { id: "3355", category: "Car Rental" },
  { id: "3356", category: "Car Rental" },
  { id: "3357", category: "Car Rental" },
  { id: "3358", category: "Car Rental" },
  { id: "3359", category: "Car Rental" },
  { id: "3360", category: "Car Rental" },
  { id: "3361", category: "Car Rental" },
  { id: "3362", category: "Car Rental" },
  { id: "3363", category: "Car Rental" },
  { id: "3364", category: "Car Rental" },
  { id: "3365", category: "Car Rental" },
  { id: "3366", category: "Car Rental" },
  { id: "3367", category: "Car Rental" },
  { id: "3368", category: "Car Rental" },
  { id: "3369", category: "Car Rental" },
  { id: "3370", category: "Car Rental" },
  { id: "3371", category: "Car Rental" },
  { id: "3372", category: "Car Rental" },
  { id: "3373", category: "Car Rental" },
  { id: "3374", category: "Car Rental" },
  { id: "3375", category: "Car Rental" },
  { id: "3376", category: "Car Rental" },
  { id: "3377", category: "Car Rental" },
  { id: "3378", category: "Car Rental" },
  { id: "3379", category: "Car Rental" },
  { id: "3380", category: "Car Rental" },
  { id: "3381", category: "Car Rental" },
  { id: "3382", category: "Car Rental" },
  { id: "3383", category: "Car Rental" },
  { id: "3384", category: "Car Rental" },
  { id: "3385", category: "Car Rental" },
  { id: "3386", category: "Car Rental" },
  { id: "3387", category: "Car Rental" },
  { id: "3388", category: "Car Rental" },
  { id: "3389", category: "Car Rental" },
  { id: "3390", category: "Car Rental" },
  { id: "3391", category: "Car Rental" },
  { id: "3392", category: "Car Rental" },
  { id: "3393", category: "Car Rental" },
  { id: "3394", category: "Car Rental" },
  { id: "3395", category: "Car Rental" },
  { id: "3396", category: "Car Rental" },
  { id: "3397", category: "Car Rental" },
  { id: "3398", category: "Car Rental" },
  { id: "3399", category: "Car Rental" },
  { id: "3400", category: "Car Rental" },
  { id: "3401", category: "Car Rental" },
  { id: "3402", category: "Car Rental" },
  { id: "3403", category: "Car Rental" },
  { id: "3404", category: "Car Rental" },
  { id: "3405", category: "Car Rental" },
  { id: "3406", category: "Car Rental" },
  { id: "3407", category: "Car Rental" },
  { id: "3408", category: "Car Rental" },
  { id: "3409", category: "Car Rental" },
  { id: "3410", category: "Car Rental" },
  { id: "3411", category: "Car Rental" },
  { id: "3412", category: "Car Rental" },
  { id: "3413", category: "Car Rental" },
  { id: "3414", category: "Car Rental" },
  { id: "3415", category: "Car Rental" },
  { id: "3416", category: "Car Rental" },
  { id: "3417", category: "Car Rental" },
  { id: "3418", category: "Car Rental" },
  { id: "3419", category: "Car Rental" },
  { id: "3420", category: "Car Rental" },
  { id: "3421", category: "Car Rental" },
  { id: "3422", category: "Car Rental" },
  { id: "3423", category: "Car Rental" },
  { id: "3424", category: "Car Rental" },
  { id: "3425", category: "Car Rental" },
  { id: "3426", category: "Car Rental" },
  { id: "3427", category: "Car Rental" },
  { id: "3428", category: "Car Rental" },
  { id: "3429", category: "Car Rental" },
  { id: "3430", category: "Car Rental" },
  { id: "3431", category: "Car Rental" },
  { id: "3432", category: "Car Rental" },
  { id: "3433", category: "Car Rental" },
  { id: "3434", category: "Car Rental" },
  { id: "3435", category: "Car Rental" },
  { id: "3436", category: "Car Rental" },
  { id: "3437", category: "Car Rental" },
  { id: "3438", category: "Car Rental" },
  { id: "3439", category: "Car Rental" },
  { id: "3440", category: "Car Rental" },
  { id: "3441", category: "Car Rental" },
  { id: "3501", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3502", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3503", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3504", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3505", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3506", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3507", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3508", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3509", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3510", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3511", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3512", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3513", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3514", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3515", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3516", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3517", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3518", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3519", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3520", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3521", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3522", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3523", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3524", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3525", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3526", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3527", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3528", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3529", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3530", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3531", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3532", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3533", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3534", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3535", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3536", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3537", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3538", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3539", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3540", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3541", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3542", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3543", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3544", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3545", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3546", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3547", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3548", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3549", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3550", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3551", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3552", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3553", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3554", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3555", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3556", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3557", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3558", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3559", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3560", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3561", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3562", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3563", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3564", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3565", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3566", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3567", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3568", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3569", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3570", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3571", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3572", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3573", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3574", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3575", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3576", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3577", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3578", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3579", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3580", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3581", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3582", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3583", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3584", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3585", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3586", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3587", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3588", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3589", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3590", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3591", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3592", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3593", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3594", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3595", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3596", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3597", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3598", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3599", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3600", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3601", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3602", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3603", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3604", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3605", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3606", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3607", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3608", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3609", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3610", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3611", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3612", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3613", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3614", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3615", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3616", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3617", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3618", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3619", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3620", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3621", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3622", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3623", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3624", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3625", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3626", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3627", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3628", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3629", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3630", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3631", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3632", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3633", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3634", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3635", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3636", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3637", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3638", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3639", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3640", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3641", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3642", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3643", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3644", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3645", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3646", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3647", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3648", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3649", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3650", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3651", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3652", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3653", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3654", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3655", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3656", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3657", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3658", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3659", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3660", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3661", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3662", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3663", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3664", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3665", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3666", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3667", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3668", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3669", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3670", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3671", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3672", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3673", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3674", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3675", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3676", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3677", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3678", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3679", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3680", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3681", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3682", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3683", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3684", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3685", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3686", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3687", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3688", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3689", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3690", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3691", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3692", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3693", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3694", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3695", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3696", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3697", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3698", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3699", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3700", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3701", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3702", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3703", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3704", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3705", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3706", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3707", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3708", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3709", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3710", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3711", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3712", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3713", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3714", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3715", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3716", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3717", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3718", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3719", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3720", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3721", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3722", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3723", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3724", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3725", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3726", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3727", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3728", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3729", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3730", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3731", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3732", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3733", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3734", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3735", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3736", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3737", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3738", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3739", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3740", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3741", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3742", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3743", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3744", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3745", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3746", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3747", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3748", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3749", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3750", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3751", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3752", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3753", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3754", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3755", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3756", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3757", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3758", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3759", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3760", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3761", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3762", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3763", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3764", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3765", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3766", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3767", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3768", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3769", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3770", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3771", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3772", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3773", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3774", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3775", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3776", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3777", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3778", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3779", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3780", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3781", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3782", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3783", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3784", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3785", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3786", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3787", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3788", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3789", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3790", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3816", category: "Hotels/Motels/Inns/Resorts" },
  { id: "3835", category: "Hotels/Motels/Inns/Resorts" },
  { id: "4011", category: "Rail Transport" },
  { id: "4111", category: "Rail Transport" },
  { id: "4112", category: "Rail Transport" },
  { id: "4119", category: "Health" },
  { id: "4121", category: "Road Transport" },
  { id: "4131", category: "Road Transport" },
  { id: "4214", category: "Other" },
  { id: "4215", category: "Other" },
  { id: "4225", category: "Other" },
  { id: "4411", category: "Water Transport" },
  { id: "4457", category: "Water Transport" },
  { id: "4468", category: "Other" },
  { id: "4511", category: "Travel" },
  { id: "4582", category: "Travel" },
  { id: "4722", category: "Travel" },
  { id: "4723", category: "Travel" },
  { id: "4784", category: "Other" },
  { id: "4789", category: "Travel" },
  { id: "4812", category: "TMT" },
  { id: "4814", category: "TMT" },
  { id: "4815", category: "TMT" },
  { id: "4816", category: "TMT" },
  { id: "4821", category: "TMT" },
  { id: "4829", category: "Other" },
  { id: "4899", category: "TMT" },
  { id: "4900", category: "Other" },
  { id: "5013", category: "Other" },
  { id: "5021", category: "Other" },
  { id: "5039", category: "Other" },
  { id: "5044", category: "Other" },
  { id: "5045", category: "Other" },
  { id: "5046", category: "Other" },
  { id: "5047", category: "Health" },
  { id: "5051", category: "Other" },
  { id: "5065", category: "Other" },
  { id: "5072", category: "Other" },
  { id: "5074", category: "Other" },
  { id: "5085", category: "Other" },
  { id: "5094", category: "Other" },
  { id: "5099", category: "Other" },
  { id: "5111", category: "Other" },
  { id: "5122", category: "Health" },
  { id: "5131", category: "Other" },
  { id: "5137", category: "Shopping" },
  { id: "5139", category: "Shopping" },
  { id: "5169", category: "Other" },
  { id: "5172", category: "Other" },
  { id: "5192", category: "Shopping" },
  { id: "5193", category: "Shopping" },
  { id: "5198", category: "Shopping" },
  { id: "5199", category: "Other" },
  { id: "5200", category: "Shopping" },
  { id: "5211", category: "Other" },
  { id: "5231", category: "Other" },
  { id: "5251", category: "Other" },
  { id: "5261", category: "Other" },
  { id: "5271", category: "Other" },
  { id: "5300", category: "Other" },
  { id: "5309", category: "Shopping" },
  { id: "5310", category: "Shopping" },
  { id: "5311", category: "Shopping" },
  { id: "5331", category: "Shopping" },
  { id: "5399", category: "Shopping" },
  { id: "5411", category: "Shopping" },
  { id: "5422", category: "Shopping" },
  { id: "5441", category: "Shopping" },
  { id: "5451", category: "Shopping" },
  { id: "5462", category: "Shopping" },
  { id: "5499", category: "Shopping" },
  { id: "5511", category: "Other" },
  { id: "5521", category: "Other" },
  { id: "5531", category: "Other" },
  { id: "5532", category: "Other" },
  { id: "5533", category: "Shopping" },
  { id: "5541", category: "Other" },
  { id: "5542", category: "Fuel" },
  { id: "5551", category: "Other" },
  { id: "5561", category: "Other" },
  { id: "5571", category: "Other" },
  { id: "5592", category: "Other" },
  { id: "5598", category: "Other" },
  { id: "5599", category: "Other" },
  { id: "5611", category: "Shopping" },
  { id: "5621", category: "Shopping" },
  { id: "5631", category: "Shopping" },
  { id: "5641", category: "Shopping" },
  { id: "5651", category: "Shopping" },
  { id: "5655", category: "Shopping" },
  { id: "5661", category: "Shopping" },
  { id: "5681", category: "Shopping" },
  { id: "5691", category: "Shopping" },
  { id: "5697", category: "Shopping" },
  { id: "5698", category: "Shopping" },
  { id: "5699", category: "Shopping" },
  { id: "5712", category: "Shopping" },
  { id: "5713", category: "Other" },
  { id: "5714", category: "Other" },
  { id: "5718", category: "Other" },
  { id: "5719", category: "Other" },
  { id: "5722", category: "Shopping" },
  { id: "5732", category: "Shopping" },
  { id: "5733", category: "Shopping" },
  { id: "5734", category: "Shopping" },
  { id: "5735", category: "Shopping" },
  { id: "5811", category: "Eating" },
  { id: "5812", category: "Eating" },
  { id: "5813", category: "Eating" },
  { id: "5814", category: "Eating" },
  { id: "5815", category: "Shopping" },
  { id: "5816", category: "Shopping" },
  { id: "5817", category: "Shopping" },
  { id: "5818", category: "Shopping" },
  { id: "5832", category: "Shopping" },
  { id: "5912", category: "Health" },
  { id: "5921", category: "Shopping" },
  { id: "5931", category: "Shopping" },
  { id: "5932", category: "Shopping" },
  { id: "5933", category: "Shopping" },
  { id: "5935", category: "Other" },
  { id: "5937", category: "Other" },
  { id: "5940", category: "Shopping" },
  { id: "5941", category: "Shopping" },
  { id: "5942", category: "Shopping" },
  { id: "5943", category: "Shopping" },
  { id: "5944", category: "Shopping" },
  { id: "5945", category: "Shopping" },
  { id: "5946", category: "Shopping" },
  { id: "5947", category: "Shopping" },
  { id: "5948", category: "Shopping" },
  { id: "5949", category: "Shopping" },
  { id: "5950", category: "Shopping" },
  { id: "5960", category: "Other" },
  { id: "5961", category: "Other" },
  { id: "5962", category: "Other" },
  { id: "5963", category: "Other" },
  { id: "5964", category: "Other" },
  { id: "5965", category: "Other" },
  { id: "5966", category: "Other" },
  { id: "5967", category: "Other" },
  { id: "5968", category: "Other" },
  { id: "5969", category: "Other" },
  { id: "5970", category: "Shopping" },
  { id: "5971", category: "Shopping" },
  { id: "5972", category: "Shopping" },
  { id: "5973", category: "Shopping" },
  { id: "5975", category: "Health" },
  { id: "5976", category: "Health" },
  { id: "5977", category: "Shopping" },
  { id: "5978", category: "Shopping" },
  { id: "5983", category: "Other" },
  { id: "5992", category: "Shopping" },
  { id: "5993", category: "Shopping" },
  { id: "5994", category: "Shopping" },
  { id: "5995", category: "Shopping" },
  { id: "5996", category: "Shopping" },
  { id: "5997", category: "Shopping" },
  { id: "5998", category: "Shopping" },
  { id: "5999", category: "Shopping" },
  { id: "6010", category: "Finance" },
  { id: "6011", category: "Finance" },
  { id: "6012", category: "Finance" },
  { id: "6051", category: "Finance" },
  { id: "6211", category: "Finance" },
  { id: "6300", category: "Finance" },
  { id: "6381", category: "Finance" },
  { id: "6399", category: "Finance" },
  { id: "6513", category: "Other" },
  { id: "7011", category: "Hotels/Motels/Inns/Resorts" },
  { id: "7012", category: "Other" },
  { id: "7032", category: "Other" },
  { id: "7033", category: "Other" },
  { id: "7210", category: "Other" },
  { id: "7211", category: "Other" },
  { id: "7216", category: "Other" },
  { id: "7217", category: "Other" },
  { id: "7221", category: "Shopping" },
  { id: "7230", category: "Shopping" },
  { id: "7251", category: "Shopping" },
  { id: "7261", category: "Other" },
  { id: "7273", category: "Other" },
  { id: "7276", category: "Other" },
  { id: "7277", category: "Other" },
  { id: "7278", category: "Other" },
  { id: "7296", category: "Other" },
  { id: "7297", category: "Other" },
  { id: "7298", category: "Other" },
  { id: "7299", category: "Other" },
  { id: "7311", category: "Other" },
  { id: "7321", category: "Finance" },
  { id: "7332", category: "Other" },
  { id: "7333", category: "Other" },
  { id: "7338", category: "Other" },
  { id: "7339", category: "Other" },
  { id: "7342", category: "Other" },
  { id: "7349", category: "Other" },
  { id: "7361", category: "Other" },
  { id: "7372", category: "Other" },
  { id: "7375", category: "Other" },
  { id: "7379", category: "Other" },
  { id: "7392", category: "Other" },
  { id: "7393", category: "Other" },
  { id: "7394", category: "Other" },
  { id: "7395", category: "Other" },
  { id: "7399", category: "Other" },
  { id: "7511", category: "Other" },
  { id: "7512", category: "Car Rental" },
  { id: "7513", category: "Other" },
  { id: "7519", category: "Other" },
  { id: "7523", category: "Other" },
  { id: "7531", category: "Other" },
  { id: "7534", category: "Other" },
  { id: "7535", category: "Other" },
  { id: "7538", category: "Other" },
  { id: "7542", category: "Other" },
  { id: "7549", category: "Other" },
  { id: "7622", category: "Other" },
  { id: "7623", category: "Other" },
  { id: "7629", category: "Other" },
  { id: "7631", category: "Other" },
  { id: "7641", category: "Other" },
  { id: "7692", category: "Other" },
  { id: "7699", category: "Other" },
  { id: "7800", category: "Other" },
  { id: "7801", category: "Other" },
  { id: "7802", category: "Other" },
  { id: "7829", category: "Other" },
  { id: "7832", category: "Entertainment" },
  { id: "7841", category: "Shopping" },
  { id: "7911", category: "Entertainment" },
  { id: "7922", category: "Entertainment" },
  { id: "7929", category: "Entertainment" },
  { id: "7932", category: "Entertainment" },
  { id: "7933", category: "Entertainment" },
  { id: "7941", category: "Entertainment" },
  { id: "7991", category: "Entertainment" },
  { id: "7992", category: "Entertainment" },
  { id: "7993", category: "Entertainment" },
  { id: "7994", category: "Entertainment" },
  { id: "7995", category: "Entertainment" },
  { id: "7996", category: "Entertainment" },
  { id: "7997", category: "Entertainment" },
  { id: "7998", category: "Entertainment" },
  { id: "7999", category: "Entertainment" },
  { id: "8011", category: "Health" },
  { id: "8021", category: "Health" },
  { id: "8031", category: "Health" },
  { id: "8041", category: "Health" },
  { id: "8042", category: "Health" },
  { id: "8043", category: "Health" },
  { id: "8044", category: "Health" },
  { id: "8049", category: "Health" },
  { id: "8050", category: "Health" },
  { id: "8062", category: "Health" },
  { id: "8071", category: "Health" },
  { id: "8099", category: "Health" },
  { id: "8111", category: "School" },
  { id: "8211", category: "School" },
  { id: "8220", category: "School" },
  { id: "8241", category: "School" },
  { id: "8244", category: "School" },
  { id: "8249", category: "School" },
  { id: "8299", category: "School" },
  { id: "8351", category: "Other" },
  { id: "8398", category: "Other" },
  { id: "8641", category: "Other" },
  { id: "8651", category: "Other" },
  { id: "8661", category: "Other" },
  { id: "8675", category: "Other" },
  { id: "8699", category: "Other" },
  { id: "8734", category: "Other" },
  { id: "8911", category: "Other" },
  { id: "8931", category: "Other" },
  { id: "8999", category: "Other" },
  { id: "9211", category: "Other" },
  { id: "9222", category: "Other" },
  { id: "9223", category: "Other" },
  { id: "9311", category: "Finance" },
  { id: "9399", category: "Other" },
  { id: "9402", category: "Other" },
  { id: "9405", category: "Other" },
  { id: "9700", category: "Other" },
  { id: "9701", category: "Other" },
  { id: "9702", category: "Other" },
  { id: "9950", category: "Other" },
];

interface GetMccCategoryParams {
  mcc: string;
}
export const getMccCategory = ({ mcc }: GetMccCategoryParams) => {
  const mccEntry = mccCategories.find(({ id }) => id === mcc);
  return mccEntry ? mccEntry.category : "";
};
